### ISSUE TITLE
Download Station issue

### ISSUE THREAD

**Issue by mythodeia** [Egorvah/DownloadStation-run-script-after-complete#1]
Thanks a lot for your script. It works fine but have an issue with DownloadStation.
After using the script the download is marked as failed even though it's completed. 
Can you explain the database scripts? Do the trigger messes up the downloadstation db someway?
Anyway, if you remember and can help i am all ears :)
Telegram integration works fine by the way :)

Thanks

**Comment by Egorvah** [comment]
For Insert or Update queries in download_queue table running trigger SYNODownloadTrigger
As I understand it, my trigger "onComplete" influence on SYNODownloadTrigger, so download tasks have warning icon status

If will drop "onComplete" trigger then status icon wil as successful

I'm dont know how to resolve this bug
